<a href="https://colab.research.google.com/github/ykim71/georgia_analysis/blob/main/(4)_Georgia_organization_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# need access to the folder(s) below:

#%cd /content/drive/MyDrive/Georgia/

/content/drive/.shortcut-targets-by-id/1YSQ9BBnwwRu7fyeM_9V6eoFgKQBPl4Rr/Georgia/Locations Analysis

# Organization analysis

## spaCy -- pulling organizations only

In [ ]:
# lemmatization if needed
import spacy
from spacy import displacy

#sp = spacy.load('en_core_web_sm')
sp = spacy.load('en_core_web_sm', disable=["tok2vec", "tagger", "parser", "attribute_ruler", "lemmatizer"])


def text_ner_org(text):
  text = sp(text)
  
  ner_list = []
  
  for entity in text.ents:
    if entity.label_ == "ORG":
      ner_list.append(entity.text + " (" + entity.label_ + ")")
    else:
      None
  return str(set(ner_list))

### org analysis

In [ ]:
import pandas as pd
df = pd.read_pickle('/content/drive/MyDrive/Georgia/Web Scraping/Georgia_data_v2_translation_ner3_lem.pkl')

/content/drive/.shortcut-targets-by-id/1YSQ9BBnwwRu7fyeM_9V6eoFgKQBPl4Rr/Georgia/Web Scraping

In [ ]:
df['ner_orgs'] = df['article_final'].astype(str).apply(text_ner_org)
df

,index,source,en_source,website,article_url,article_title,article_author,date_published,article_final,ner_places,ner_orgs,article_lemma_num,id,ner_places_orgs,ner_person
0,0,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_167b17...,American Pickers to film in Georgia,NaN,2022-09-19,The American Pickers are excited to return to ...,"{'America (GPE)', 'Georgia (GPE)'}","{'The History Channel (ORG)', 'CDC (ORG)', 'Am...",american picker excited return georgia plan fi...,1,"{American Pickers (ORG), Georgia (GPE), CDC (O...",{Pickers (PERSON)}
1,1,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_248646...,Free Covid test kits available TODAY,NaN,2022-09-15,Candler County Health Department and Southeast...,{'Metter (GPE)'},"{'SE Broad Street (ORG)', 'Candler County Heal...",candler county health department southeast hea...,2,"{Metter (GPE), Candler County Health Departmen...",{Covid (PERSON)}
2,2,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_2eccfd...,CLASS OF 2000 STILL LEADS THE WAY! Over $29K r...,NaN,2022-10-14,After the third week of the Education Foundati...,set(),"{'Brian & Kathleen Tootle (ORG)', 'The Educati...",week education foundation 2022 campaign class ...,3,"{Brian & Kathleen Tootle (ORG), The Education ...","{Melinda Franklin (PERSON), Jenny Brantley (PE..."
3,3,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_2f555e...,"MMS Lady Tigers to play for championship, MMS ...",NaN,2022-09-27,Congratulations to the Metter Middle School La...,"{'South Tattnall (GPE)', 'Bryan County (GPE)',...","{'MHS (ORG)', 'the Metter Middle School Lady T...",congratulation metter middle school lady tiger...,4,"{Toombs County (GPE), MHS (ORG), Bryan County ...",{South Tattnall (PERSON)}
4,4,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_2fe7f1...,ATTN Hunters & Anglers: Celebrate Hunting & Fi...,NaN,2022-09-22,In a proclamation recently signed by Gov. Bria...,{'Georgia (GPE)'},"{'Outdoor Adventure Days (ORG)', 'the Georgia ...",proclamation recently sign gov brian kemp satu...,5,"{Outdoor Adventure Days (ORG), the Georgia Dep...","{Brian Kemp (PERSON), Richard Nixon (PERSON)}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/magazine/sports-su...,Sports superstitions: Fans embrace traditions ...,STUART STEELE,2022-10-07,Superstitions are an inherent part of the fabr...,"{'Cincinnati (GPE)', 'Mississippi State (GPE)'...","{'File/Staff (ORG)', 'Auburn (ORG)', 'Louisian...",superstition inherent fabric life campus unive...,496,"{Auburn (ORG), Georgia (GPE), Jersey (GPE), At...","{Thomason (PERSON), Alex Arena (PERSON), Katie..."
496,496,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/magazine/the-pagan...,The Pagans of Athens,ELIZABETH RYMAREV,2022-10-07,"Presence. â€œ[Paganism is about] being here, in ...","{'Yule (GPE)', 'Wicca (GPE)', 'Earth (LOC)', '...","{'Athens Area Pagans (ORG)', 'the Wicked Witch...",presence paganism space lachele foley say acc...,497,"{Wicca (GPE), Pagan (GPE), Earth (LOC), West (...","{Mabon (PERSON), Jim Grimes (PERSON), Pagan (P..."
497,497,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/multimedia/between...,Between the Headphones: Bulldog success agains...,STUART STEELE,2022-10-11,"In this episode, sports editor Stuart Steele s...",{'Georgia (GPE)'},{'Auburn (ORG)'},episode sport editor stuart steele speak footb...,498,"{Georgia (GPE), Auburn (ORG)}","{Stuart Steele (PERSON), Parth Patel (PERSON)}"
498,498,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/multimedia/between...,Between the Headphones: Close game at Missour...,STUART STEELE,2022-10-04,Sports editor Stuart Steele speaks to football...,"{'Missouri (GPE)', 'Georgia (GPE)'}",set(),sport editor stuart steele speak football beat...,499,"{Georgia (GPE), Missouri (GPE)}","{Stuart Steele (PERSON), Parth Patel (PERSON),..."
499,499,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/multimedia/between...,"Between the Headphones: Defeating Kent State, ...",STUART STEELE,2022-09-27,Sports editor Stuart Steele speaks to football...,"{'Missouri (GPE)', 'Georgia (GPE)'}",{'Kent State (ORG)'},sport editor stuart steele speak football beat...,500,"{Georgia (GPE), Kent State (ORG), Missouri (GPE)}","{Stuart Steele (PERSON), Parth Patel (PERSON),..."

In [ ]:
df['date_published'].agg(['min', 'max']) #CO: Minor detail: In case you want to simplify and save a line, consider using this

min    2022-09-15
max    2022-10-15
Name: date_published, dtype: object

In [ ]:
df_ner_comp_no_set = df[df['ner_orgs'] != 'set()']

In [ ]:
df_ner_comp_no_set

,index,source,en_source,website,article_url,article_title,article_author,date_published,article_final,ner_places,ner_orgs,article_lemma_num,id,ner_places_orgs,ner_person
0,0,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_167b17...,American Pickers to film in Georgia,NaN,2022-09-19,The American Pickers are excited to return to ...,"{'America (GPE)', 'Georgia (GPE)'}","{'The History Channel (ORG)', 'CDC (ORG)', 'Am...",american picker excited return georgia plan fi...,1,"{American Pickers (ORG), Georgia (GPE), CDC (O...",{Pickers (PERSON)}
1,1,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_248646...,Free Covid test kits available TODAY,NaN,2022-09-15,Candler County Health Department and Southeast...,{'Metter (GPE)'},"{'SE Broad Street (ORG)', 'Candler County Heal...",candler county health department southeast hea...,2,"{Metter (GPE), Candler County Health Departmen...",{Covid (PERSON)}
2,2,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_2eccfd...,CLASS OF 2000 STILL LEADS THE WAY! Over $29K r...,NaN,2022-10-14,After the third week of the Education Foundati...,set(),"{'Brian & Kathleen Tootle (ORG)', 'The Educati...",week education foundation 2022 campaign class ...,3,"{Brian & Kathleen Tootle (ORG), The Education ...","{Melinda Franklin (PERSON), Jenny Brantley (PE..."
3,3,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_2f555e...,"MMS Lady Tigers to play for championship, MMS ...",NaN,2022-09-27,Congratulations to the Metter Middle School La...,"{'South Tattnall (GPE)', 'Bryan County (GPE)',...","{'MHS (ORG)', 'the Metter Middle School Lady T...",congratulation metter middle school lady tiger...,4,"{Toombs County (GPE), MHS (ORG), Bryan County ...",{South Tattnall (PERSON)}
4,4,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_2fe7f1...,ATTN Hunters & Anglers: Celebrate Hunting & Fi...,NaN,2022-09-22,In a proclamation recently signed by Gov. Bria...,{'Georgia (GPE)'},"{'Outdoor Adventure Days (ORG)', 'the Georgia ...",proclamation recently sign gov brian kemp satu...,5,"{Outdoor Adventure Days (ORG), the Georgia Dep...","{Brian Kemp (PERSON), Richard Nixon (PERSON)}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,494,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/magazine/sowing-se...,Sowing seeds: Young Urban Farmers fosters yout...,ERIN KENNEY,2022-09-29,The West Broad Community Garden is showing off...,"{'West Broad (GPE)', 'Florida (GPE)', 'mvelasq...","{""Athens Land Trust's (ORG)"", 'Photo/Melanie V...",west broad community garden show summer bounty...,495,"{Athens Land Trust's (ORG), Georgia (GPE), Par...","{Tony (PERSON), Scott (PERSON), Heather Benham..."
495,495,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/magazine/sports-su...,Sports superstitions: Fans embrace traditions ...,STUART STEELE,2022-10-07,Superstitions are an inherent part of the fabr...,"{'Cincinnati (GPE)', 'Mississippi State (GPE)'...","{'File/Staff (ORG)', 'Auburn (ORG)', 'Louisian...",superstition inherent fabric life campus unive...,496,"{Auburn (ORG), Georgia (GPE), Jersey (GPE), At...","{Thomason (PERSON), Alex Arena (PERSON), Katie..."
496,496,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/magazine/the-pagan...,The Pagans of Athens,ELIZABETH RYMAREV,2022-10-07,"Presence. â€œ[Paganism is about] being here, in ...","{'Yule (GPE)', 'Wicca (GPE)', 'Earth (LOC)', '...","{'Athens Area Pagans (ORG)', 'the Wicked Witch...",presence paganism space lachele foley say acc...,497,"{Wicca (GPE), Pagan (GPE), Earth (LOC), West (...","{Mabon (PERSON), Jim Grimes (PERSON), Pagan (P..."
497,497,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/multimedia/between...,Between the Headphones: Bulldog success agains...,STUART STEELE,2022-10-11,"In this episode, sports editor Stuart Steele s...",{'Georgia (GPE)'},{'Auburn (ORG)'},episode sport editor stuart steele speak footb...,498,"{Georgia (GPE), Auburn (ORG)}","{Stuart Steele (PERSON), Parth Patel (PERSON)}"
499,499,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/multimedia/between...,"Between the Headphones: Defeating Kent State, ...",STUART STEELE,2022-09-27,Sports editor Stuart Steele speaks to football...,"{'Missouri (GPE)', 'Georgia (GPE)'}",{'Kent State (ORG)'},sport editor stuart steele speak football beat...,500,"{Georgia (GPE), Kent State (ORG), Missouri (GPE)}","{Stuart Steele (PERSON), Parth Patel (PERSON),..."

In [ ]:
print(len(df_ner_comp_no_set))
print(len(df))

483
500

In [ ]:
s = df_ner_comp_no_set['ner_orgs'].astype(str).str.split(',').explode().str.strip('{} ')
s #CO: looks like this gives us a column with all the recognized orgs

0                   'The History Channel (ORG)'
0                                   'CDC (ORG)'
0                      'American Pickers (ORG)'
1                       'SE Broad Street (ORG)'
1      'Candler County Health Department (ORG)'
                         ...
496                  'Athens Area Pagans (ORG)'
496                    'the Wicked Witch (ORG)'
496                               'Islam (ORG)'
497                              'Auburn (ORG)'
499                          'Kent State (ORG)'
Name: ner_orgs, Length: 3881, dtype: object

In [ ]:
s_df = pd.DataFrame(s)

In [ ]:
s_df['id'] = s_df.index + 1
s_df

                                     ner_orgs   id
0                 'The History Channel (ORG)'    1
0                                 'CDC (ORG)'    1
0                    'American Pickers (ORG)'    1
1                     'SE Broad Street (ORG)'    2
1    'Candler County Health Department (ORG)'    2
..                                        ...  ...
496                'Athens Area Pagans (ORG)'  497
496                  'the Wicked Witch (ORG)'  497
496                             'Islam (ORG)'  497
497                            'Auburn (ORG)'  498
499                        'Kent State (ORG)'  500

[3881 rows x 2 columns]

In [ ]:
# strip quotation mark
s_df['ner_orgs'] = s_df['ner_orgs'].str.strip('\'')
s_df['ner_orgs'] = s_df['ner_orgs'].str.strip('\"')

# strip text + parantheses 
s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r"\(.*\)","")

# # strip space in the last character
# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip('\'s')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip('\â€™s')


# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip('\'')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip()

# s_df['ner_orgs'] = s_df['ner_orgs'].str.strip('\'')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.strip('\"')

# # #
# # s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'â€œ', '')

# remove 'a '
s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^the state ', '')
s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^The state ', '')
s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^the ', '')
s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^The ', '')
s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^an ', '')
s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^a ', '')

s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip()

# # strip space in the last character
# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip('\'s')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip('\â€™s')



# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip('\'s')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip('\â€™s')

# s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^\'', '')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^\â€˜', '')

# s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^\â€œ', '')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^â€™s ', '')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^â€¢ ', '')


# s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^\'', '')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip('\'')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip('\'s')
# s_df['ner_orgs'] = s_df['ner_orgs'].str.rstrip('\â€™s')

#

<ipython-input-17-aac3f0bcd77c>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r"\(.*\)","")
<ipython-input-17-aac3f0bcd77c>:23: FutureWarning: The default value of regex will change from True to False in a future version.
  s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^the state ', '')
<ipython-input-17-aac3f0bcd77c>:24: FutureWarning: The default value of regex will change from True to False in a future version.
  s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^The state ', '')
<ipython-input-17-aac3f0bcd77c>:25: FutureWarning: The default value of regex will change from True to False in a future version.
  s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^the ', '')
<ipython-input-17-aac3f0bcd77c>:26: FutureWarning: The default value of regex will change from True to False in a future version.
  s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^The ', '')
<ipython-input-17-aac3f0bcd77c>:27: FutureWarning: The default value of regex will change from True to False in a future version.
  s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^an ', '')
<ipython-input-17-aac3f0bcd77c>:28: FutureWarning: The default value of regex will change from True to False in a future version.
  s_df['ner_orgs'] = s_df['ner_orgs'].str.replace(r'^a ', '')

In [ ]:
s_df

                             ner_orgs   id
0                     History Channel    1
0                                 CDC    1
0                    American Pickers    1
1                     SE Broad Street    2
1    Candler County Health Department    2
..                                ...  ...
496                Athens Area Pagans  497
496                      Wicked Witch  497
496                             Islam  497
497                            Auburn  498
499                        Kent State  500

[3881 rows x 2 columns]

In [ ]:
# drop duplicates
s_df_nodup = s_df.drop_duplicates()

In [ ]:
# minimal + delete the/a
print(len(s_df_nodup))
print(len(s_df))

3828
3881

In [ ]:
# minimal
print(len(s_df_nodup)) ### CO: this and the next few blocks seem to be duplicates.
print(len(s_df))

1146941
1149027

In [ ]:
# not deleting the/a
print(len(s_df_nodup))
print(len(s_df))

1135858
1149027

In [ ]:
print(len(s_df_nodup))
print(len(s_df))

1114561
1149027

In [ ]:
df_ner_comp_no_set_st = df_ner_comp_no_set[['id', 'source', 'article_final']]
df_ner_comp_no_set_st

      id             source                                      article_final
0      1  Metter Advertiser  The American Pickers are excited to return to ...
1      2  Metter Advertiser  Candler County Health Department and Southeast...
2      3  Metter Advertiser  After the third week of the Education Foundati...
3      4  Metter Advertiser  Congratulations to the Metter Middle School La...
4      5  Metter Advertiser  In a proclamation recently signed by Gov. Bria...
..   ...                ...                                                ...
494  495    The Red & Black  The West Broad Community Garden is showing off...
495  496    The Red & Black  Superstitions are an inherent part of the fabr...
496  497    The Red & Black  Presence. â€œ[Paganism is about] being here, in ...
497  498    The Red & Black  In this episode, sports editor Stuart Steele s...
499  500    The Red & Black  Sports editor Stuart Steele speaks to football...

[483 rows x 3 columns]

In [ ]:
df_ner_comp_no_set_st = pd.merge(df_ner_comp_no_set_st, s_df_nodup, how='left', on='id')

In [ ]:
df_ner_comp_no_set_st

,id,source,article_final,ner_orgs
0,1,Metter Advertiser,The American Pickers are excited to return to ...,History Channel
1,1,Metter Advertiser,The American Pickers are excited to return to ...,CDC
2,1,Metter Advertiser,The American Pickers are excited to return to ...,American Pickers
3,2,Metter Advertiser,Candler County Health Department and Southeast...,SE Broad Street
4,2,Metter Advertiser,Candler County Health Department and Southeast...,Candler County Health Department
...,...,...,...,...
3823,497,The Red & Black,"Presence. â€œ[Paganism is about] being here, in ...",Athens Area Pagans
3824,497,The Red & Black,"Presence. â€œ[Paganism is about] being here, in ...",Wicked Witch
3825,497,The Red & Black,"Presence. â€œ[Paganism is about] being here, in ...",Islam
3826,498,The Red & Black,"In this episode, sports editor Stuart Steele s...",Auburn
3827,500,The Red & Black,Sports editor Stuart Steele speaks to football...,Kent State

,id,source,article_final,ner_orgs
0,1,Metter Advertiser,The American Pickers are excited to return to ...,American Pickers
1,1,Metter Advertiser,The American Pickers are excited to return to ...,CDC
2,1,Metter Advertiser,The American Pickers are excited to return to ...,American Pickers TV Show
3,2,Metter Advertiser,Candler County Health Department and Southeast...,SE Broad Street and
4,2,Metter Advertiser,Candler County Health Department and Southeast...,Southeast Health Unit
...,...,...,...,...
1126717,192185,WALB TV 10 (NBC),Meagan Muhlbach stood by and let herself get h...,Childrenâ€™s Miracle Network
1126718,192189,WALB TV 10 (NBC),Saturday marked the sixth time in the series h...,Crimson Tide
1126719,192193,WALB TV 10 (NBC),Lexington Police are investigating the city's ...,Lexington Police
1126720,192194,WALB TV 10 (NBC),"Members and volunteers of Junior Achievement, ...",Junior Achievement
1126721,192194,WALB TV 10 (NBC),"Members and volunteers of Junior Achievement, ...",Ramey Elementary School

In [ ]:
ner_art_count = df_ner_comp_no_set_st.groupby('ner_orgs')['id'].count().reset_index()
ner_art_count #CO: Something seems wrong here. Under "ner_orgs" I'm seeing things like ".9" (row 0) and "*Prepare"

                                               ner_orgs  id
0                                                    .9   1
1      2.Be Skeptical of Unsolicited Messages: Be aware   1
2            2020 Dietary Guidelines Advisory Committee   1
3                                     2020 Disney/Pixar   1
4     2020 National Highway Traffic Safety Administr...   1
...                                                 ...  ..
2815                                          â€¢ Prepare   1
2816                                           â€¢ Preste   1
2817                                         â€¢ Seizures   1
2818               â€¢ Standalone Prescription Drug Plans   1
2819                                            â€¢ Trust   1

[2820 rows x 2 columns]

In [ ]:
ner_art_count_c5 = ner_art_count[ner_art_count['id'] >= 5]
ner_art_count_c5 #here, the orgs generally look correct but some potential issues are also observed, like "Crosswords" (row 546), "Inc." (1085), "omicron" (1529), "Parmesan" (1562), "photo credit" (1596). Also seeing ner_orgs called "taco" or "un".

                                        ner_orgs  id
22                                           ACC   9
30                                         ACCPD   7
196                                       Auburn   8
197                            Auburn University   5
267                                        Bites   5
295                                 Booktrib.com   5
319                                      Bulldog   8
321                                     Bulldogs  13
337                                          CDC  10
354                                        COVID   5
355                                     COVID-19  33
411   Centers for Disease Control and Prevention  11
415                                      Centros   5
500                                         Como  10
509                                     Congress   6
546                                   Crosswords  26
552                                 Culinary.net   5
678                                       Editor   9
687                                           El   6
751                                          FDA  11
771                              Family Features  26
798                                  Five Points   5
884                             Georgia Football   5
888                        Georgia Museum of Art   5
908                                 Getty Images  19
909                            Getty Images Plus  12
1047                                Hooks Chapel   5
1085                                        Inc.   6
1149                       Kennedy Funeral Homes   7
1150                                  Kent State  11
1171                                          LG   5
1304                                    Medicare  10
1496                                    Nonstick   5
1529                                     Omicron   5
1562                                    Parmesan   6
1596                                Photo Credit   6
1604                     Photo/Sidney Chansamone  10
1693                                 Red & Black  49
1750                                         SEC  10
1789                                    Servings  16
1809                                         Sin  11
1838                    Southern Brewing Company   6
1862                                  StatePoint  22
1961                                      Tigers  13
2027                                         UGA  17
2082                       University of Georgia  59
2090                     University of Georgia's   6
2092                     University of Georgiaâ€™s  11
2246                                          al   6
2277                                        casa   6
2286                                        como   9
2369                                      de los   7
2406                                  el Control   6
2705                                 para ayudar   6
2764                                        taco   5
2778                                          un  38
2791                                      yardas   5

In [ ]:
ner_art_count_c5 = ner_art_count_c5.sort_values('ner_orgs')
ner_art_count_c5

                                        ner_orgs  id
22                                           ACC   9
30                                         ACCPD   7
196                                       Auburn   8
197                            Auburn University   5
267                                        Bites   5
295                                 Booktrib.com   5
319                                      Bulldog   8
321                                     Bulldogs  13
337                                          CDC  10
354                                        COVID   5
355                                     COVID-19  33
411   Centers for Disease Control and Prevention  11
415                                      Centros   5
500                                         Como  10
509                                     Congress   6
546                                   Crosswords  26
552                                 Culinary.net   5
678                                       Editor   9
687                                           El   6
751                                          FDA  11
771                              Family Features  26
798                                  Five Points   5
884                             Georgia Football   5
888                        Georgia Museum of Art   5
908                                 Getty Images  19
909                            Getty Images Plus  12
1047                                Hooks Chapel   5
1085                                        Inc.   6
1149                       Kennedy Funeral Homes   7
1150                                  Kent State  11
1171                                          LG   5
1304                                    Medicare  10
1496                                    Nonstick   5
1529                                     Omicron   5
1562                                    Parmesan   6
1596                                Photo Credit   6
1604                     Photo/Sidney Chansamone  10
1693                                 Red & Black  49
1750                                         SEC  10
1789                                    Servings  16
1809                                         Sin  11
1838                    Southern Brewing Company   6
1862                                  StatePoint  22
1961                                      Tigers  13
2027                                         UGA  17
2082                       University of Georgia  59
2090                     University of Georgia's   6
2092                     University of Georgiaâ€™s  11
2246                                          al   6
2277                                        casa   6
2286                                        como   9
2369                                      de los   7
2406                                  el Control   6
2705                                 para ayudar   6
2764                                        taco   5
2778                                          un  38
2791                                      yardas   5

In [ ]:
ner_art_count_c5 = ner_art_count_c5.reset_index()
ner_art_count_c5

    index                                    ner_orgs  id
0      22                                         ACC   9
1      30                                       ACCPD   7
2     196                                      Auburn   8
3     197                           Auburn University   5
4     267                                       Bites   5
5     295                                Booktrib.com   5
6     319                                     Bulldog   8
7     321                                    Bulldogs  13
8     337                                         CDC  10
9     354                                       COVID   5
10    355                                    COVID-19  33
11    411  Centers for Disease Control and Prevention  11
12    415                                     Centros   5
13    500                                        Como  10
14    509                                    Congress   6
15    546                                  Crosswords  26
16    552                                Culinary.net   5
17    678                                      Editor   9
18    687                                          El   6
19    751                                         FDA  11
20    771                             Family Features  26
21    798                                 Five Points   5
22    884                            Georgia Football   5
23    888                       Georgia Museum of Art   5
24    908                                Getty Images  19
25    909                           Getty Images Plus  12
26   1047                                Hooks Chapel   5
27   1085                                        Inc.   6
28   1149                       Kennedy Funeral Homes   7
29   1150                                  Kent State  11
30   1171                                          LG   5
31   1304                                    Medicare  10
32   1496                                    Nonstick   5
33   1529                                     Omicron   5
34   1562                                    Parmesan   6
35   1596                                Photo Credit   6
36   1604                     Photo/Sidney Chansamone  10
37   1693                                 Red & Black  49
38   1750                                         SEC  10
39   1789                                    Servings  16
40   1809                                         Sin  11
41   1838                    Southern Brewing Company   6
42   1862                                  StatePoint  22
43   1961                                      Tigers  13
44   2027                                         UGA  17
45   2082                       University of Georgia  59
46   2090                     University of Georgia's   6
47   2092                     University of Georgiaâ€™s  11
48   2246                                          al   6
49   2277                                        casa   6
50   2286                                        como   9
51   2369                                      de los   7
52   2406                                  el Control   6
53   2705                                 para ayudar   6
54   2764                                        taco   5
55   2778                                          un  38
56   2791                                      yardas   5

In [ ]:
# delete some unrelated entities by manual review
ner_art_count_c5 = ner_art_count_c5.iloc[0:34641,] #CO: why?
ner_art_count_c5

    index                                    ner_orgs  id
0      22                                         ACC   9
1      30                                       ACCPD   7
2     196                                      Auburn   8
3     197                           Auburn University   5
4     267                                       Bites   5
5     295                                Booktrib.com   5
6     319                                     Bulldog   8
7     321                                    Bulldogs  13
8     337                                         CDC  10
9     354                                       COVID   5
10    355                                    COVID-19  33
11    411  Centers for Disease Control and Prevention  11
12    415                                     Centros   5
13    500                                        Como  10
14    509                                    Congress   6
15    546                                  Crosswords  26
16    552                                Culinary.net   5
17    678                                      Editor   9
18    687                                          El   6
19    751                                         FDA  11
20    771                             Family Features  26
21    798                                 Five Points   5
22    884                            Georgia Football   5
23    888                       Georgia Museum of Art   5
24    908                                Getty Images  19
25    909                           Getty Images Plus  12
26   1047                                Hooks Chapel   5
27   1085                                        Inc.   6
28   1149                       Kennedy Funeral Homes   7
29   1150                                  Kent State  11
30   1171                                          LG   5
31   1304                                    Medicare  10
32   1496                                    Nonstick   5
33   1529                                     Omicron   5
34   1562                                    Parmesan   6
35   1596                                Photo Credit   6
36   1604                     Photo/Sidney Chansamone  10
37   1693                                 Red & Black  49
38   1750                                         SEC  10
39   1789                                    Servings  16
40   1809                                         Sin  11
41   1838                    Southern Brewing Company   6
42   1862                                  StatePoint  22
43   1961                                      Tigers  13
44   2027                                         UGA  17
45   2082                       University of Georgia  59
46   2090                     University of Georgia's   6
47   2092                     University of Georgiaâ€™s  11
48   2246                                          al   6
49   2277                                        casa   6
50   2286                                        como   9
51   2369                                      de los   7
52   2406                                  el Control   6
53   2705                                 para ayudar   6
54   2764                                        taco   5
55   2778                                          un  38
56   2791                                      yardas   5

In [ ]:
ner_art_count_c5

    index                                    ner_orgs  id
0      22                                         ACC   9
1      30                                       ACCPD   7
2     196                                      Auburn   8
3     197                           Auburn University   5
4     267                                       Bites   5
5     295                                Booktrib.com   5
6     319                                     Bulldog   8
7     321                                    Bulldogs  13
8     337                                         CDC  10
9     354                                       COVID   5
10    355                                    COVID-19  33
11    411  Centers for Disease Control and Prevention  11
12    415                                     Centros   5
13    500                                        Como  10
14    509                                    Congress   6
15    546                                  Crosswords  26
16    552                                Culinary.net   5
17    678                                      Editor   9
18    687                                          El   6
19    751                                         FDA  11
20    771                             Family Features  26
21    798                                 Five Points   5
22    884                            Georgia Football   5
23    888                       Georgia Museum of Art   5
24    908                                Getty Images  19
25    909                           Getty Images Plus  12
26   1047                                Hooks Chapel   5
27   1085                                        Inc.   6
28   1149                       Kennedy Funeral Homes   7
29   1150                                  Kent State  11
30   1171                                          LG   5
31   1304                                    Medicare  10
32   1496                                    Nonstick   5
33   1529                                     Omicron   5
34   1562                                    Parmesan   6
35   1596                                Photo Credit   6
36   1604                     Photo/Sidney Chansamone  10
37   1693                                 Red & Black  49
38   1750                                         SEC  10
39   1789                                    Servings  16
40   1809                                         Sin  11
41   1838                    Southern Brewing Company   6
42   1862                                  StatePoint  22
43   1961                                      Tigers  13
44   2027                                         UGA  17
45   2082                       University of Georgia  59
46   2090                     University of Georgia's   6
47   2092                     University of Georgiaâ€™s  11
48   2246                                          al   6
49   2277                                        casa   6
50   2286                                        como   9
51   2369                                      de los   7
52   2406                                  el Control   6
53   2705                                 para ayudar   6
54   2764                                        taco   5
55   2778                                          un  38
56   2791                                      yardas   5

In [ ]:
#ner_art_count_c5.to_excel('Georgia_ner_orgs_art_c5_v1_pre.xlsx')

In [ ]:
ner_art_count_c5 = ner_art_count_c5.sort_values('ner_orgs', ascending=False) #CO: why sort it?
ner_art_count_c5

    index                                    ner_orgs  id
56   2791                                      yardas   5
55   2778                                          un  38
54   2764                                        taco   5
53   2705                                 para ayudar   6
52   2406                                  el Control   6
51   2369                                      de los   7
50   2286                                        como   9
49   2277                                        casa   6
48   2246                                          al   6
47   2092                     University of Georgiaâ€™s  11
46   2090                     University of Georgia's   6
45   2082                       University of Georgia  59
44   2027                                         UGA  17
43   1961                                      Tigers  13
42   1862                                  StatePoint  22
41   1838                    Southern Brewing Company   6
40   1809                                         Sin  11
39   1789                                    Servings  16
38   1750                                         SEC  10
37   1693                                 Red & Black  49
36   1604                     Photo/Sidney Chansamone  10
35   1596                                Photo Credit   6
34   1562                                    Parmesan   6
33   1529                                     Omicron   5
32   1496                                    Nonstick   5
31   1304                                    Medicare  10
30   1171                                          LG   5
29   1150                                  Kent State  11
28   1149                       Kennedy Funeral Homes   7
27   1085                                        Inc.   6
26   1047                                Hooks Chapel   5
25    909                           Getty Images Plus  12
24    908                                Getty Images  19
23    888                       Georgia Museum of Art   5
22    884                            Georgia Football   5
21    798                                 Five Points   5
20    771                             Family Features  26
19    751                                         FDA  11
18    687                                          El   6
17    678                                      Editor   9
16    552                                Culinary.net   5
15    546                                  Crosswords  26
14    509                                    Congress   6
13    500                                        Como  10
12    415                                     Centros   5
11    411  Centers for Disease Control and Prevention  11
10    355                                    COVID-19  33
9     354                                       COVID   5
8     337                                         CDC  10
7     321                                    Bulldogs  13
6     319                                     Bulldog   8
5     295                                Booktrib.com   5
4     267                                       Bites   5
3     197                           Auburn University   5
2     196                                      Auburn   8
1      30                                       ACCPD   7
0      22                                         ACC   9

In [ ]:
#ner_art_count_c5.to_excel('Georgia_ner_orgs_art_c5_v2_add.xlsx')

## org topic count



> v1 and v2 is due to changes in the dataset; the purpose of v2 is to find those that are not included in the v1 (or round1).

> comparisions of v1 and v2 is included

In [ ]:
%cd /content/drive/MyDrive/Georgia/Organization Analysis

/content/drive/.shortcut-targets-by-id/1YSQ9BBnwwRu7fyeM_9V6eoFgKQBPl4Rr/Georgia/Organization Analysis

In [ ]:
org_v2 = pd.read_excel('Georgia_ner_orgs_art_c5_v2.xlsx') #CO: not clear to me what the meaning of having these two different sheets are? They will later become different columns, I see. But not sure where they were created? Are they somehow used to check each other?
org_v1 = pd.read_excel('Georgia_ner_orgs_art_c5_v1_pre.xlsx')

In [ ]:
org_v1 #CO: several of the entries under "ner_orgs" look strange. Like symbols or generic words.

       Unnamed: 0                              ner_orgs   id
0               0                                   NaN  284
1              24    & Movement Disorders Support Group   23
2              29                                & SIâ€™s   33
3              39                                   & Â©   24
4              44                       'American Idol'    5
...           ...                                   ...  ...
21371      154800  â€¢ Standalone Prescription Drug Plans   17
21372      154826                               â€¢ Trust   17
21373      154852      â€¢Danielsville Evangelical Church    8
21374      154861        â€¢Lighthouse Pentecostal Church    6
21375      154904                                     ðŸŸ£    8

[21376 rows x 3 columns]

In [ ]:
org_v1['version'] = 'v1'
org_v2['version'] = 'v2'

In [ ]:
org_merge = pd.merge(org_v1, org_v2, how='outer', on=["ner_orgs"])

In [ ]:
org_merge

,Unnamed: 0,ner_orgs,id_x,version_x,id_y,version_y
0,0.0,NaN,284.0,v1,27.0,v2
1,92026.0,NaN,28.0,v1,27.0,v2
2,24.0,& Movement Disorders Support Group,23.0,v1,NaN,NaN
3,29.0,& SIâ€™s,33.0,v1,NaN,NaN
4,39.0,& Â©,24.0,v1,NaN,NaN
...,...,...,...,...,...,...
35409,NaN,Zuckerman Museum of Art,NaN,NaN,5.0,v2
35410,NaN,Zwangobani,NaN,NaN,8.0,v2
35411,NaN,Zyan Royal,NaN,NaN,6.0,v2
35412,NaN,Zyon McCollum,NaN,NaN,10.0,v2
35413,NaN,Zyon Mckenzie,NaN,NaN,8.0,v2

In [ ]:
org_merge_st = org_merge[['ner_orgs', 'version_x', 'version_y', 'id_y']]
org_merge_st

                                 ner_orgs version_x version_y  id_y
0                                     NaN        v1        v2  27.0
1                                     NaN        v1        v2  27.0
2      & Movement Disorders Support Group        v1       NaN   NaN
3                                  & SIâ€™s        v1       NaN   NaN
4                                     & Â©        v1       NaN   NaN
...                                   ...       ...       ...   ...
35409             Zuckerman Museum of Art       NaN        v2   5.0
35410                          Zwangobani       NaN        v2   8.0
35411                          Zyan Royal       NaN        v2   6.0
35412                       Zyon McCollum       NaN        v2  10.0
35413                       Zyon Mckenzie       NaN        v2   8.0

[35414 rows x 4 columns]

In [ ]:
org_merge_repeat = org_merge_st[ (org_merge_st['version_x']=='v1') & (org_merge_st['version_y']=="v2")]

In [ ]:
org_merge_repeat

                                      ner_orgs version_x version_y  id_y
0                                          NaN        v1        v2  27.0
1                                          NaN        v1        v2  27.0
19     1.A Clear Understanding of Your Purpose        v1        v2  16.0
20                           10 Downing Street        v1        v2   5.0
21                                        100k        v1        v2  16.0
...                                        ...       ...       ...   ...
20562             Zoological Society of London        v1        v2   6.0
20563                                     Zoom        v1        v2  12.0
20564                               Zuckerberg        v1        v2  17.0
20565                                     Zulu        v1        v2  20.0
20567                    Zuzu African Acrobats        v1        v2  10.0

[19593 rows x 4 columns]

In [ ]:
#org_merge_repeat.to_excel('Georgia_ner_orgs_art_c5_repeat.xlsx')

In [ ]:
df

,index,source,en_source,website,article_url,article_title,article_author,date_published,article_final,ner_places,ner_orgs,article_lemma_num,id,ner_places_orgs,ner_person
0,0,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_167b17...,American Pickers to film in Georgia,NaN,2022-09-19,The American Pickers are excited to return to ...,"{'America (GPE)', 'Georgia (GPE)'}","{'The History Channel (ORG)', 'CDC (ORG)', 'Am...",american picker excited return georgia plan fi...,1,"{American Pickers (ORG), Georgia (GPE), CDC (O...",{Pickers (PERSON)}
1,1,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_248646...,Free Covid test kits available TODAY,NaN,2022-09-15,Candler County Health Department and Southeast...,{'Metter (GPE)'},"{'SE Broad Street (ORG)', 'Candler County Heal...",candler county health department southeast hea...,2,"{Metter (GPE), Candler County Health Departmen...",{Covid (PERSON)}
2,2,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_2eccfd...,CLASS OF 2000 STILL LEADS THE WAY! Over $29K r...,NaN,2022-10-14,After the third week of the Education Foundati...,set(),"{'Brian & Kathleen Tootle (ORG)', 'The Educati...",week education foundation 2022 campaign class ...,3,"{Brian & Kathleen Tootle (ORG), The Education ...","{Melinda Franklin (PERSON), Jenny Brantley (PE..."
3,3,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_2f555e...,"MMS Lady Tigers to play for championship, MMS ...",NaN,2022-09-27,Congratulations to the Metter Middle School La...,"{'South Tattnall (GPE)', 'Bryan County (GPE)',...","{'MHS (ORG)', 'the Metter Middle School Lady T...",congratulation metter middle school lady tiger...,4,"{Toombs County (GPE), MHS (ORG), Bryan County ...",{South Tattnall (PERSON)}
4,4,Metter Advertiser,1.0,http://www.metteradvertiser.com/,http://www.metteradvertiser.com/article_2fe7f1...,ATTN Hunters & Anglers: Celebrate Hunting & Fi...,NaN,2022-09-22,In a proclamation recently signed by Gov. Bria...,{'Georgia (GPE)'},"{'Outdoor Adventure Days (ORG)', 'the Georgia ...",proclamation recently sign gov brian kemp satu...,5,"{Outdoor Adventure Days (ORG), the Georgia Dep...","{Brian Kemp (PERSON), Richard Nixon (PERSON)}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/magazine/sports-su...,Sports superstitions: Fans embrace traditions ...,STUART STEELE,2022-10-07,Superstitions are an inherent part of the fabr...,"{'Cincinnati (GPE)', 'Mississippi State (GPE)'...","{'File/Staff (ORG)', 'Auburn (ORG)', 'Louisian...",superstition inherent fabric life campus unive...,496,"{Auburn (ORG), Georgia (GPE), Jersey (GPE), At...","{Thomason (PERSON), Alex Arena (PERSON), Katie..."
496,496,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/magazine/the-pagan...,The Pagans of Athens,ELIZABETH RYMAREV,2022-10-07,"Presence. â€œ[Paganism is about] being here, in ...","{'Yule (GPE)', 'Wicca (GPE)', 'Earth (LOC)', '...","{'Athens Area Pagans (ORG)', 'the Wicked Witch...",presence paganism space lachele foley say acc...,497,"{Wicca (GPE), Pagan (GPE), Earth (LOC), West (...","{Mabon (PERSON), Jim Grimes (PERSON), Pagan (P..."
497,497,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/multimedia/between...,Between the Headphones: Bulldog success agains...,STUART STEELE,2022-10-11,"In this episode, sports editor Stuart Steele s...",{'Georgia (GPE)'},{'Auburn (ORG)'},episode sport editor stuart steele speak footb...,498,"{Georgia (GPE), Auburn (ORG)}","{Stuart Steele (PERSON), Parth Patel (PERSON)}"
498,498,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/multimedia/between...,Between the Headphones: Close game at Missour...,STUART STEELE,2022-10-04,Sports editor Stuart Steele speaks to football...,"{'Missouri (GPE)', 'Georgia (GPE)'}",set(),sport editor stuart steele speak football beat...,499,"{Georgia (GPE), Missouri (GPE)}","{Stuart Steele (PERSON), Parth Patel (PERSON),..."
499,499,The Red & Black,1.0,https://www.redandblack.com/,https://www.redandblack.com/multimedia/between...,"Between the Headphones: Defeating Kent State, ...",STUART STEELE,2022-09-27,Sports editor Stuart Steele speaks to football...,"{'Missouri (GPE)', 'Georgia (GPE)'}",{'Kent State (ORG)'},sport editor stuart steele speak football beat...,500,"{Georgia (GPE), Kent State (ORG), Missouri (GPE)}","{Stuart Steele (PERSON), Parth Patel (PERSON),..."

In [ ]:
#%cd /content/drive/MyDrive/Georgia/Organization Analysis

org_merge_repeat = pd.read_excel('Georgia_ner_orgs_art_c5_repeat.xlsx')

In [ ]:
org_merge_repeat.tail(50)

,Unnamed: 0,ner_orgs,version_x,version_y,id_y
19541,20228,Willies Estrada,v1,v2,5
19542,20231,Willmore,v1,v2,5
19543,20242,Wilmington Police Department,v1,v2,5
19544,20251,Winder City Council,v1,v2,5
19545,20270,Windsor Castleâ€™s,v1,v2,5
19546,20275,Wine Spectator,v1,v2,5
19547,20278,Wingfoot XC Classic,v1,v2,5
19548,20290,Winthrop,v1,v2,5
19549,20298,Wisconsin Historical Society State,v1,v2,5
19550,20299,Wisconsin Public Radio,v1,v2,5
19551,20307,Wizard,v1,v2,5
19552,20311,WolfSpeed,v1,v2,5
19553,20312,Wolffork Baptist Church,v1,v2,5
19554,20313,Wolffork Church Road,v1,v2,5
19555,20314,Wolfman,v1,v2,5
19556,20321,Womanâ€™s,v1,v2,5
19557,20325,Women's Meeting Tuesdays,v1,v2,5
19558,20367,World Champion,v1,v2,5
19559,20383,Wormuth,v1,v2,5
19560,20393,Wymore Arbor State,v1,v2,5
19561,20396,X2304 & X2602,v1,v2,5
19562,20397,X2748,v1,v2,5
19563,20398,XBB,v1,v2,5
19564,20399,XIV,v1,v2,5
19565,20401,XXL Magazine,v1,v2,5
19566,20415,Xfinity Series Playoff,v1,v2,5
19567,20423,YHC,v1,v2,5
19568,20426,YOA,v1,v2,5
19569,20443,Yahoo News National,v1,v2,5
19570,20444,Yahoo News Senior,v1,v2,5
19571,20453,Yakima Police Department,v1,v2,5
19572,20455,Yale Climate Connections,v1,v2,5
19573,20457,Yale Law Schoolâ€™s Veterans Legal Services Clinic,v1,v2,5
19574,20471,Yeah Yeah Yeahs,v1,v2,5
19575,20478,Yenin,v1,v2,5
19576,20481,YikYak,v1,v2,5
19577,20484,Yolo County Sheriffâ€™s Office,v1,v2,5
19578,20490,Yoonâ€™s Defense Ministry,v1,v2,5
19579,20496,YouTubers,v1,v2,5
19580,20500,Young Life,v1,v2,5
19581,20516,ZOE,v1,v2,5
19582,20517,ZOE LOFGREN/,v1,v2,5
19583,20524,Zaphorizhzhia Nuclear Power Plant,v1,v2,5
19584,20526,Zaporizhzhia Nuclear Power Plantâ€™s,v1,v2,5
19585,20527,Zaporizhzhia Nuclear Power Station,v1,v2,5
19586,20532,Zatko $,v1,v2,5
19587,20542,Zichal,v1,v2,5
19588,20546,Zimmermanâ€™s,v1,v2,5
19589,20549,Zion Custis,v1,v2,5
19590,20554,Zipties,v1,v2,5

In [ ]:
short_orgs = org_merge_repeat[org_merge_repeat['ner_orgs'].str.len() <= 5]
short_orgs.head(50)
#CO: just doing some additional inspection in this chunk. In some the chunk I noticed some weird-looking names in the "ner_orgs" column ...
#... but that seems to be better here. Still, there are some where we might ask ourselves whether it's really organizations being identified. Like the words "inc." or "Trump". Same as "TD" and "NL" which seems like they could mean anything.
# ...also thinking of words like "VIDEO" or "Smith" or "Jones" or "Court"

     Unnamed: 0 ner_orgs version_x version_y  id_y
1           290       AP        v1        v2  7110
3         12652      NFL        v1        v2  4877
10         2854      CBS        v1        v2  3628
12         9010    House        v1        v2  3033
13        17048    State        v1        v2  2806
15        18221    Trump        v1        v2  2576
16         9355     Inc.        v1        v2  2574
18        15076      RBI        v1        v2  2440
19         5965      ERA        v1        v2  2419
20         3053      CNN        v1        v2  2379
21         7494      GOP        v1        v2  2338
23         6515      FBI        v1        v2  2098
29        12739      NPR        v1        v2  1800
30         5971     ESPN        v1        v2  1669
34        17444       TD        v1        v2  1557
35        15855      SEC        v1        v2  1547
40        12571      NBA        v1        v2  1337
42         2975      CDC        v1        v2  1246
47        12708       NL        v1        v2  1102
49        12003     Mets        v1        v2  1086
53        12582      NBC        v1        v2  1048
57         6525      FDA        v1        v2   990
68         7134     Ford        v1        v2   895
74        19122    VIDEO        v1        v2   848
79        16670    Smith        v1        v2   786
80        11316      MLB        v1        v2   780
82         8395     HOST        v1        v2   777
83        13122     Navy        v1        v2   771
84          137      ABC        v1        v2   750
85         1210     Army        v1        v2   750
87        10000     KDKA        v1        v2   744
89         1084    Apple        v1        v2   733
95        12686      NHL        v1        v2   705
97        16273    Scott        v1        v2   688
98         8361      HBO        v1        v2   684
104       10591      LSU        v1        v2   665
107        8813     Hill        v1        v2   650
108       12543     NASA        v1        v2   646
112       11241    MAJOR        v1        v2   631
113       20133    White        v1        v2   628
118       11371      MVP        v1        v2   607
121        6519      FBS        v1        v2   603
125       19628     WTOC        v1        v2   591
127       10985    Lions        v1        v2   588
128       12592     NCAA        v1        v2   587
131        9864    Jones        v1        v2   576
132        4746    Court        v1        v2   574
145       17915    Times        v1        v2   540
152       17294      Sun        v1        v2   532
154       11324      MLS        v1        v2   529

In [ ]:
# CO: Doing some additional checking here

# If "ner_orgs" cointain numbers, it could mean that something is being misidentified. Just using "2" as an example here, and noticeted that "2022" is identified as an organization
# ... same with Season 2 and B12 and I-285 and "9/23/2022"
orgs_with_symbol = org_merge_repeat[org_merge_repeat['ner_orgs'].str.contains('2')]
print(len(orgs_with_symbol)) #CO: about 150 instances for "2"; might be worth checking if other numbers cause issues
orgs_with_symbol.head(50)

158

,Unnamed: 0,ner_orgs,version_x,version_y,id_y
25,4664,Copyright 2022 The Associated Press,v1,v2,2005
242,2862,CBS 2's,v1,v2,358
290,45,2022,v1,v2,311
373,2859,CBS 2,v1,v2,244
391,14135,Pac-12,v1,v2,235
496,4665,Copyright Â© 2022,v1,v2,190
575,3664,Channel 2 Action News,v1,v2,167
801,4666,Copyright Â© 2022 Press-Sentinel,v1,v2,124
809,5628,District 2,v1,v2,123
890,8879,Hocus Pocus 2,v1,v2,114
954,2946,CBS2 News,v1,v2,107
1119,3663,Channel 2,v1,v2,93
1292,6347,Episode 2,v1,v2,82
1482,5987,ESPN2,v1,v2,73
1563,9176,I-285,v1,v2,69
1662,1276,Associated Press Top 25,v1,v2,65
2109,3667,Channel 2â€²s,v1,v2,53
2204,4663,Copyright 2022,v1,v2,51
2268,13571,O2 Arena,v1,v2,50
2548,13412,Nord Stream 2,v1,v2,45
2577,1542,B12,v1,v2,44
2697,19603,WRDW News 12,v1,v2,43
3111,15829,SB 202,v1,v2,37
3317,16312,Season 2,v1,v2,35
3456,18793,United 2,v1,v2,34
3546,14733,Portland 2,v1,v2,33
3695,41,2020 Census,v1,v2,31
3945,15749,Rule 12,v1,v2,30
4059,10826,Layer 2-4,v1,v2,29
4166,6579,FOX 12,v1,v2,28
4176,7908,Georgians 21,v1,v2,28
4303,2863,CBS 2â€™s,v1,v2,27
4327,4631,Cook 2-3 minutes,v1,v2,27
4545,2861,CBS 2 Investigators,v1,v2,26
4704,42,2020 Dietary Guidelines Advisory Committee,v1,v2,25
4705,43,2020 National Highway Traffic Safety Administr...,v1,v2,25
4707,119,A24,v1,v2,25
4807,4569,Connect2Prevent,v1,v2,25
5095,19109,VBZ-US-2126,v1,v2,25
5148,1576,BCL-XL/BCL-2,v1,v2,24
5437,18033,TradingChallenge2022,v1,v2,24
5453,19536,WJCL 22 News,v1,v2,24
5466,82,9/23/2022,v1,v2,23
5732,3871,Chickamauga American Legion Post 217,v1,v2,22
5901,13976,P. 2012,v1,v2,22
5936,15909,SOCCR2,v1,v2,22
5989,19355,Voice Season 22,v1,v2,22
6110,7932,Ghosts Season 2,v1,v2,21
6185,13411,Nord Stream 1 and 2,v1,v2,21
6260,39,2012,v1,v2,20

In [ ]:
#CO: 

orgs_with_symbol = org_merge_repeat[org_merge_repeat['ner_orgs'].str.contains('#')]
print(len(orgs_with_symbol)) #CO: very few instances
print(orgs_with_symbol.head(50))

7
       Unnamed: 0          ner_orgs version_x version_y  id_y
3472         1487  Austin Cindric #        v1        v2    33
8512         1490     Austin Hill #        v1        v2    14
17067         105         A. Hill #        v1        v2     5
17318        2205  Blaine Perkins #        v1        v2     5
17601        4680      Corey Heim #        v1        v2     5
17682        5294   Dean Thompson #        v1        v2     5
18233        9796     Jesse Iwuji #        v1        v2     5

In [ ]:
orgs_with_symbol = org_merge_repeat[org_merge_repeat['ner_orgs'].str.contains('/')] #CO. ner_orgs with "dashes could be problematic"
print(len(orgs_with_symbol)) #CO: a few hundreds instances
orgs_with_symbol.head(50)

217

,Unnamed: 0,ner_orgs,version_x,version_y,id_y
1507,16189,Savannah/Hilton Head International Airport,v1,v2,72
2047,307,AP Photo/,v1,v2,54
2157,1285,Associated Press/Report for America Statehouse...,v1,v2,52
2351,7457,GEMA/HS,v1,v2,48
2690,18155,Triple-A Scranton/Wilkes-Barre,v1,v2,43
2705,2022,Bertrand Calmeau/CBS,v1,v2,42
2841,3328,Capitol Beat/Georgia News Collaborative Poll,v1,v2,40
3347,323,AP Photo/John Raoux,v1,v2,34
3461,20247,Win McNamee/Getty Images,v1,v2,34
3470,1085,Apple - https://apple.co/3ISD6Ve,v1,v2,33
3585,313,AP Photo/Carolyn Kaster,v1,v2,32
3690,19656,WXIX/Gray News,v1,v2,32
4129,1643,BSSO/BSSE,v1,v2,28
4340,5722,Donnell Suggs/The Atlanta Voice,v1,v2,27
4363,7928,Getty Images/iStockphoto,v1,v2,27
4394,10076,KMOV/Gray News,v1,v2,27
4464,16188,Savannah/Chatham Board of Education,v1,v2,27
4493,18036,Trae Patton/NBC,v1,v2,27
4762,2933,CBS SF/BCN,v1,v2,25
4768,3056,CNN/Pool,v1,v2,25
4901,9398,Infant/Toddler,v1,v2,25
4909,9708,Janssen/Johnson & Johnson,v1,v2,25
4924,10661,Laboratory/Test Information,v1,v2,25
5040,16613,Sirius/XM Podcast Let's,v1,v2,25
5104,19580,WOIO/Gray News,v1,v2,25
5148,1576,BCL-XL/BCL-2,v1,v2,24
5466,82,9/23/2022,v1,v2,23
5875,12516,NA/AA,v1,v2,22
6250,19633,WTVG/Gray News,v1,v2,21
6265,318,AP Photo/Evan Vucci,v1,v2,20
6266,336,AP Photo/Wilfredo Lee,v1,v2,20
6302,2944,CBS/AP,v1,v2,20
6413,10144,KVVU /Gray News,v1,v2,20
6414,10145,KVVU/Gray News,v1,v2,20
6545,19562,WMBF/Gray News,v1,v2,20
6610,3327,Capitol Beat/Georgia News Collaborative,v1,v2,19
6801,16960,St. Josephâ€™s/Candler,v1,v2,19
6997,8548,HarperCollins/Zondervan,v1,v2,18
7024,10110,KSEE/KGPE,v1,v2,18
7218,1613,BNCollege.com/insight/report/college2030,v1,v2,17
7246,2958,CBSDFW.COM/AP,v1,v2,17
7480,13710,Office of Infectious Disease and HIV/AIDS Policy,v1,v2,17
7514,15345,Reissued 9/23/2022,v1,v2,17
7648,1301,Astrid Stawiarz/Getty Images,v1,v2,16
7747,6057,Eastern/Central,v1,v2,16
7768,6973,Flagler/Volusia County Line,v1,v2,16
8019,19333,Visite LLS.org/es para obtener,v1,v2,16
8023,19525,WIS /Gray News,v1,v2,16
8046,329,AP Photo/Phelan M. Ebenhack,v1,v2,15
8210,8746,Hermitâ€™s Peak/Calf Canyon Fire,v1,v2,15

In [ ]:
print(len(org_merge_repeat))

19591

In [ ]:
import re

symbols = r'[*@â‚¬$#%\=Â©?!\"\\|~_(){}<>]' ## CO: when ner_orgs have symbols like these, it can also signal issues. Many of the examples below look at bit strange.
orgs_with_symbols = org_merge_repeat[org_merge_repeat['ner_orgs'].str.contains(re.compile(symbols))]
print(len(orgs_with_symbols)) #CO: Of course, this is just 46 instances in a large dataset, so maybe it's not a big deal because some noice is acceptable.
orgs_with_symbols.head(50)

46

,Unnamed: 0,ner_orgs,version_x,version_y,id_y
496,4665,Copyright Â© 2022,v1,v2,190
801,4666,Copyright Â© 2022 Press-Sentinel,v1,v2,124
1460,12536,NAPSI)â€”If,v1,v2,74
2922,6925,First Alert Forecast @ 9PM,v1,v2,39
3472,1487,Austin Cindric #,v1,v2,33
3825,216,AFavakeh@savannahnow.com,v1,v2,30
3975,91,@jaybusbee,v1,v2,29
4867,7970,Giving = Living,v1,v2,25
4951,12535,NAPSI)â€”Earlier,v1,v2,25
5435,17910,Tim) Banks,v1,v2,24
5783,7122,Food!,v1,v2,22
5844,10570,LNwogu@gannett.com,v1,v2,22
6261,84,@Coolio,v1,v2,20
6665,6923,First Alert Forecast @,v1,v2,19
6968,6924,First Alert Forecast @ 4PM,v1,v2,18
8042,92,@selah,v1,v2,15
8512,1490,Austin Hill #,v1,v2,14
8869,14769,Powell $,v1,v2,14
8994,89,@carolinesiede,v1,v2,13
9286,10210,KatesG@cbsnews.com,v1,v2,13
9701,3832,Chicago Bears @,v1,v2,12
10477,5514,Detroit Lions @,v1,v2,11
11013,85,@GSAthletics_FB,v1,v2,10
11014,90,@garanceburke,v1,v2,10
11423,9532,Investigative@ap.org,v1,v2,10
12118,5184,Dan) McCarney,v1,v2,9
14955,14970,Pusan \u200b\u200bInternational Film Festival,v1,v2,7
15296,86,@MurphyAJC,v1,v2,6
15373,1187,Arizona Cardinals @,v1,v2,6
15386,1352,Atlanta Falcons @,v1,v2,6
16313,12024,Miami Dolphins @,v1,v2,6
16320,12167,Minnesota Vikings @,v1,v2,6
16405,13203,New England Patriots @,v1,v2,6
16996,19780,Washington Commanders @,v1,v2,6
17063,87,@NateSlack5,v1,v2,5
17067,105,A. Hill #,v1,v2,5
17318,2205,Blaine Perkins #,v1,v2,5
17393,2951,CBS3@4,v1,v2,5
17601,4680,Corey Heim #,v1,v2,5
17682,5294,Dean Thompson #,v1,v2,5
18233,9796,Jesse Iwuji #,v1,v2,5
18670,13273,NewCelebrityExtra@gmail.com,v1,v2,5
19315,18307,Twitter @H_Schoenbaum,v1,v2,5
19316,18308,Twitter/@NashWX/CNN,v1,v2,5
19437,19362,Volodymyr) Zelenskyy,v1,v2,5
19586,20532,Zatko $,v1,v2,5